#Manual steps:
#on github-runner machine we need to run below commands to authorize git hub
#gh auth login
#gh auth refresh -h github.com -s admin:org

- name: create github dir
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    mode: '0711'

- name: download & extract Runner content
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz
    dest: /actions-runner
    remote_src: yes

- name: download github cli
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: install github cli
  ansible.builtin.dnf:
    name: gh
    state: latest

- name: get github runner token
  ansible.builtin.shell: 'gh api   --method POST   -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/AkshayreddyDevops/actions/runners/registration-token|jq .token'
  register: token
- name: git runner list
  ansible.builtin.shell: 'gh api    -H "Accept: application/vnd.github+json"   -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/AkshayreddyDevops/actions/runners|jq .total_count'
  register: runner_count

- name: output
  ansible.legacy.debug:
    msg: "{{ runner_count.stdout }}"

- name: configure runner and start if not running
  when: runner_count.stdout | int  > 2
  block:
    - name: configure github runner
      ansible.builtin.shell: ./config.sh --url https://github.com/AkshayreddyDevops --token {{ token.stdout }} --unattended --runnergroup Default --name ec2 --labels rhel --work _work --replace
      args: 
        chdir: /actions-runner
      become_user: ec2-user
    - name: install & start runner service on github runner
      ansible.builtin.shell: ./svc.sh install ; ./svc.sh start
      args:
        chdir: /action-runner