name: provision tools infra
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: ec2
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init -backend-config=env-dev/state.tfvars
        

