name: provision infra
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: cd to /home/ec2-user/gitRepo/tools-infra/infra/state.tf
        run: /home/ec2-user/gitRepo/tools-infra/infra
      - name: Terraform init
        run: terraform init -backend-config=/home/ec2-user/gitRepo/tools-infra/infra/state.tf


