name: provision infra
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init -backend-config=env_dev/state.tfvars
      - name: Terraform plan
        run: terraform plan -var-file=env_dev/main.tfvars


#Hello test

