name: provision infra
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        run: terraform init


#Hello test

